### ISSUE TITLE
[Dev branch] Text background/box not rendering

### ISSUE THREAD

**Issue by GameBurrow** [klyte45/DynamicTextProps#16]
Tested your dev branch due to klyte45/TransportLinesManager/issues/57 and noticed that in current dev branch, text renderers don't render background and the box around it.

### Example 1
On this image you can see that the black background is not rendering thus asset original destination display appears
![image](https://user-images.githubusercontent.com/4341091/115071906-8929d000-9eff-11eb-8d89-cae002e64b53.png)
should look like this (this from Steam release version)
![image](https://user-images.githubusercontent.com/4341091/115075756-3ef71d80-9f04-11eb-9feb-0a59bb778bcb.png)

### Example 2
Or here you can see that the text is floating in air
![image](https://user-images.githubusercontent.com/4341091/115071996-a8286200-9eff-11eb-99a3-e3908c5ab067.png)
should look like this (this from Steam release version)
![image](https://user-images.githubusercontent.com/4341091/115075786-49b1b280-9f04-11eb-94af-775bc4fda0ef.png)

Branch: https://github.com/klyte45/WriteTheSigns/tree/dev/klyte
Last commit on the branch at the time of testing: e786e2b7ae43fce50ae9f1189c7e4f309f4849e4

**Comment by klyte45** [comment]
Well, the dev/klyte branch wasn't intended to be a testeable branch. It's my current development branch and might eventually have problems.

I'm doing some changes in my repositories to allow having pre-release branches, like an alpha branch in the case of WTS (since the mod itself still under beta release). Wait for news on that soon right after the beta 3 release in Workshop.

In time: this issue is already solved in next commit of WTS.

**Comment by klyte45** [comment]
Btw, alpha branch is available now: https://github.com/klyte45/WriteTheSigns/tree/alpha

Feel free to test it. If no one finds a problem, it will be released until Monday.
A TLM beta branch update is to be done in next hours to match exactly this version of WTS, but the current must be compatible.

**Comment by GameBurrow** [comment]
Seems like fixed. Though I had to use TLM from your dev branch. If I use alpha or dev version of WTS with release TLM or dev TLM with release WTS, then the game render engine blows up (UI breaks, vehicles stop rendering, buildings some render some don't and lighting flashes).

Current TLM dev has a bug that it resets prefix data (everything related to prefixes: prefix name, budget settings and even vehicle selection), don't know if you're aware of it.

**Comment by klyte45** [comment]
I see... Well, the new WTS will need the new TLM to work properly since there's mutual dependency between them (when using both together). The problem is the TLM is currently under a big reform as said in [this TLM issue comment](https://github.com/klyte45/TransportLinesManager/issues/52#issuecomment-822020373). I was planning to release both this weekend but it seems that will need to be postponed to next month.

**Comment by GameBurrow** [comment]
No worries, keep up the good work!

I'll just redo my prefixes and keep using the current WTS alpha and TLM dev version until you release the updates, because I want the model selector fix ;)

**Comment by klyte45** [comment]
The WTS alpha was updated. The TLM 14 beta branch will be available soon too. Take a look later!

In time: [TLM Alpha branch available](https://github.com/klyte45/WriteTheSigns/tree/alpha). Isn't final but will be maintained stable
